# Generated by Django 2.0 on 2017-12-28 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefact',
            name='id',
        ),
        migrations.AlterField(
            model_name='artefact',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='keeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='number',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='title',
            field=models.CharField(default='noname', max_length=256),
        ),
    ]
