# Generated by Django 2.0 on 2017-12-28 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0002_auto_20171228_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='keeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
