# Generated by Django 2.0.1 on 2018-01-12 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import warehouse.nomenclature.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artefact', models.FileField(upload_to=warehouse.nomenclature.models.artefact_rename)),
                ('title', models.CharField(max_length=256)),
                ('pages', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
