CREATE TABLE if not exists pdf_pages (id INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT UNIQUE ON CONFLICT ROLLBACK NOT NULL ON CONFLICT ROLLBACK, pdf_id INTEGER NOT NULL ON CONFLICT ROLLBACK, hashed_name STRING (32) UNIQUE ON CONFLICT ROLLBACK NOT NULL ON CONFLICT ROLLBACK);

CREATE TABLE if not exists pdf_files (id INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT UNIQUE ON CONFLICT ROLLBACK NOT NULL ON CONFLICT ROLLBACK, name STRING NOT NULL ON CONFLICT ROLLBACK, hashed_name STRING (32) UNIQUE ON CONFLICT ROLLBACK NOT NULL ON CONFLICT ROLLBACK, loaded DATETIME NOT NULL ON CONFLICT ROLLBACK DEFAULT (datetime('now', 'localtime')), published DATETIME, user_id INTEGER NOT NULL ON CONFLICT ROLLBACK, pages INTEGER);

CREATE TABLE users (id INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT UNIQUE ON CONFLICT ROLLBACK NOT NULL ON CONFLICT ROLLBACK, name STRING UNIQUE ON CONFLICT ROLLBACK NOT NULL ON CONFLICT ROLLBACK, password STRING (64) NOT NULL ON CONFLICT ROLLBACK);

INSERT INTO users (name, password) values ('user', '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8');

COMMIT;
